# Generated by Django 3.2.7 on 2021-12-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='date',
            new_name='created_at',
        ),
    ]
