# Generated by Django 3.2.7 on 2021-12-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_rename_date_tweet_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='user',
        ),
    ]
